# This file contains the fastlane.tools configuration for iOS
# You can find the documentation at https://docs.fastlane.tools
# For a list of all available actions, check out https://docs.fastlane.tools/actions
# For a list of all available plugins, check out https://docs.fastlane.tools/plugins/available-plugins

default_platform(:ios)

platform :ios do
  desc "Capture des screenshots pour iOS"
  lane :screenshots do
    capture_screenshots(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      devices: ["iPhone 16 Pro", "iPhone 16", "iPhone SE (3rd generation)"],
      languages: ["en-US"],
      output_directory: "./fastlane/screenshots",
      number_of_retries: 1, # Réduit le nombre d’essais pour chaque écran
      stop_after_first_error: true, # Arrête immédiatement en cas d'erreur
      clear_previous_screenshots: true # Efface les anciennes captures avant de démarrer
    )
  end

  desc "Generate and upload screenshots to App Store Connect"
  lane :upload_screenshots do
    capture_screenshots(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      output_directory: "./fastlane/screenshots"
    )
    deliver(
      force: true,
      skip_metadata: true,
      skip_screenshots: false
    )
  end
end
