# This file contains the fastlane.tools configuration for Android
# You can find the documentation at https://docs.fastlane.tools
# For a list of all available actions, check out https://docs.fastlane.tools/actions
# For a list of all available plugins, check out https://docs.fastlane.tools/plugins/available-plugins

default_platform(:android)

platform :android do
  desc "Exécute les tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Prendre des screenshots Android"
  lane :screenshots do
    capture_screenshots(
      output_directory: './fastlane/screenshots',  # Dossier pour stocker les screenshots
      devices: ['Nexus 5', 'Pixel 4'],  # Appareils Android à utiliser pour capturer les screenshots
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
