# This file contains the fastlane.tools configuration for Android
# You can find the documentation at https://docs.fastlane.tools
# For a list of all available actions, check out https://docs.fastlane.tools/actions
# For a list of all available plugins, check out https://docs.fastlane.tools/plugins/available-plugins

default_platform(:android)

platform :android do
  desc "Exécute les tests"
  lane :test do
    gradle(task: "test")
  end

  lane :screenshots do
    # Exécuter la commande Flutter pour construire l'APK
    sh("flutter build apk --release")
    sh("flutter build apk --debug")
  
    # Utiliser screengrab pour capturer les screenshots avec l'APK généré
    screengrab(
      app_apk_path: "./../build/app/outputs/flutter-apk/app-release.apk",
      tests_apk_path: "./../build/app/outputs/flutter-apk/app-debug.apk",
      output_directory: "./fastlane/screenshots"
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
